# arguments for dataset
dataset: pretrain
nclass: 16
crop_size: 512
data_root: 'data_root'
total_iters: 120000
lr: 0.00005
batch_size: 12
lr_multi: 1.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95
amp: True
workers: 1
ignore_index: 255
validate_interval: 2000
log_interval: 200
save_interval: 20000
eval_mode: original